package com.jwg.notebook.gui.button;

import com.jwg.notebook.screens.menuScreen;

import java.io.FileWriter;
import java.io.IOException;

import static com.jwg.notebook.screens.menuScreen.bookmarkedpage;

public class gotobookmark {
    public static void onPress() {
        bookmarkedpage = menuScreen.page;
        writeBookmark();
    }
    private static void writeBookmark() {
        try {
            FileWriter fileOverwriter = new FileWriter("config/vanilla-notebook/bookmark.cfg");
            fileOverwriter.write("# This file stores the bookmark data; DO NOT EDIT THIS FILE as it can cause issues, bugs and crashing!\n"+bookmarkedpage);
            fileOverwriter.close();
        } catch (IOException e) { e.printStackTrace(); }
    }
}
